/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.JOptionPane;
import trabalhopraticoi.Caminhao;
import trabalhopraticoi.Carro;
import trabalhopraticoi.Onibus;
import trabalhopraticoi.Veiculo;
import trabalhopraticoi.Veiculos;

/**
 *
 * @author Bruno and Matheus
 */
public class CadastroVeiculo extends javax.swing.JInternalFrame {
    protected static Veiculos veiculos = new Veiculos();
    /**
     * Creates new form CadastroVeiculo
     */
    public CadastroVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        labelPlaca = new javax.swing.JLabel();
        txt_placa = new javax.swing.JTextField();
        txt_ano = new javax.swing.JTextField();
        labelAno = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        txt_valorDiaria = new javax.swing.JTextField();
        check_carro = new javax.swing.JCheckBox();
        check_caminhao = new javax.swing.JCheckBox();
        check_onibus = new javax.swing.JCheckBox();
        labelPor = new javax.swing.JLabel();
        txt_numPort = new javax.swing.JTextField();
        txt_numPass = new javax.swing.JTextField();
        labelPassa = new javax.swing.JLabel();
        txt_medKmLt = new javax.swing.JTextField();
        labelMedia = new javax.swing.JLabel();
        labelCategoria = new javax.swing.JLabel();
        txt_categoria = new javax.swing.JTextField();
        labelAr = new javax.swing.JLabel();
        check_ar = new javax.swing.JCheckBox();
        check_wifi = new javax.swing.JCheckBox();
        labelWifi = new javax.swing.JLabel();
        txt_numEixos = new javax.swing.JTextField();
        labelCarga = new javax.swing.JLabel();
        txt_cargMax = new javax.swing.JTextField();
        labelEixos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_salva = new javax.swing.JButton();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(396, 346));

        labelPlaca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPlaca.setText("Placa:");

        labelAno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelAno.setText("Ano:");

        labelValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelValor.setText("Valor diária:");

        check_carro.setText("Carro");
        check_carro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_carroActionPerformed(evt);
            }
        });

        check_caminhao.setText("Caminhão");
        check_caminhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_caminhaoActionPerformed(evt);
            }
        });

        check_onibus.setText("Onibus");
        check_onibus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_onibusActionPerformed(evt);
            }
        });

        labelPor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPor.setText("Nº Portas:");

        labelPassa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPassa.setText("Nº Passageiros:");

        labelMedia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelMedia.setText("Média Km/L:");

        labelCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelCategoria.setText("Categoria:");

        labelAr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelAr.setText("Arcondicionado:");

        labelWifi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelWifi.setText("Wifi:");

        labelCarga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelCarga.setText("Carga Max.:");

        labelEixos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelEixos.setText("Nº de Eixos:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(labelPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(labelAno, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_ano))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(labelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_valorDiaria)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelEixos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txt_numEixos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cargMax, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPassa, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelPor, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_numPort)
                                    .addComponent(txt_numPass)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(labelMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txt_medKmLt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(144, 144, 144))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(labelWifi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(check_wifi))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(labelAr, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(check_ar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(check_carro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(check_onibus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(check_caminhao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_onibus)
                    .addComponent(check_carro)
                    .addComponent(check_caminhao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPlaca)
                            .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAno)
                            .addComponent(txt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelValor)
                            .addComponent(txt_valorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCategoria)
                            .addComponent(txt_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPor)
                            .addComponent(txt_numPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPassa)
                            .addComponent(txt_numPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMedia)
                            .addComponent(txt_medKmLt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAr, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(check_ar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check_wifi)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelEixos)
                                .addComponent(labelCarga)
                                .addComponent(txt_cargMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_numEixos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelWifi))))
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("NOVO VEICULO");

        btn_salva.setText("Salvar");
        btn_salva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(btn_salva, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btn_salva)
                .addGap(37, 37, 37))
        );

        setSize(new java.awt.Dimension(636, 413));
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Instacia um novo veiculo ja com sua definicao de carro, onibus ou caminhao, e retorna o
     * veiculo instanciado ou caso haja erro, returna null.
     * @return novoVeiculo ou null
     */
    private Veiculo salvaVeiculo(){
        int ano = Integer.parseInt(txt_ano.getText());
        float valorDiaria = Float.parseFloat(txt_valorDiaria.getText());
        String placa = txt_placa.getText();
        if(check_caminhao.isSelected()){
            int numEixos = Integer.parseInt(txt_numEixos.getText());
            float cargMax = Float.parseFloat(txt_cargMax.getText());
            Veiculo novoVeiculo = new Caminhao(placa, ano, valorDiaria, numEixos, cargMax);
            return novoVeiculo;
        }else if(check_carro.isSelected()){
            int     numPass = Integer.parseInt(txt_numPass.getText());
            int numPort = Integer.parseInt(txt_numPort.getText());
            float medKmLt = Float.parseFloat(txt_medKmLt.getText());
            Veiculo novoVeiculo = new Carro(placa, ano, valorDiaria, numPass, numPort, medKmLt, check_ar.isSelected());
            return novoVeiculo;
        }else if(check_onibus.isSelected()){
            int numPass = Integer.parseInt(txt_numPass.getText());
            Veiculo novoVeiculo = new Onibus(placa, ano, valorDiaria, numPass, txt_categoria.getText(), check_wifi.isSelected(), check_ar.isSelected());
            return novoVeiculo;
        }
        
        return null;
    }
    
    /**
     * Muda as opcoes de marcar da interface grafica para habilitada ou desabilidade,
     * dependendo do valor recebido por paramentro. Tal valor, do tipo boolean.
     * @param valor
     */
    protected void opsCaminhao(boolean valor){
        if (valor){
            txt_cargMax.setEnabled(true);
            txt_numEixos.setEnabled(true);
            check_caminhao.setEnabled(true);
        } else{
            txt_cargMax.setEnabled(false);
            txt_numEixos.setEnabled(false);
            check_caminhao.setEnabled(false);
        }
    }
    
    /**
     * Muda as opcoes de marcar da interface grafica para habilitada ou desabilidade,
     * dependendo do valor recebido por paramentro. Tal valor, do tipo boolean.
     * @param valor
     */
    protected void opsOnibus(boolean valor){
        if(valor){
            check_onibus.setEnabled(true);
            txt_numPass.setEnabled(true);
            check_ar.setEnabled(true);
            check_wifi.setEnabled(true);
            txt_categoria.setEnabled(true);
        }else{
            check_onibus.setEnabled(false);
            txt_numPass.setEnabled(false);
            check_ar.setEnabled(false);
            check_wifi.setEnabled(false);
            txt_categoria.setEnabled(false);
        }
    }
    
    /**
     * Muda as opcoes de marcar da interface grafica para habilitada ou desabilidade,
     * dependendo do valor recebido por paramentro. Tal valor, do tipo boolean.
     * @param valor
     */
    protected void opsCarro(boolean valor){
        if(valor){
            txt_numPass.setEnabled(true);
            check_carro.setEnabled(true);
            txt_numPort.setEnabled(true);
            check_ar.setEnabled(true);
            txt_medKmLt.setEnabled(true);
        }else{
            txt_numPass.setEnabled(false);
            check_carro.setEnabled(false);
            txt_numPort.setEnabled(false);
            check_ar.setEnabled(false);
            txt_medKmLt.setEnabled(false);
        }
    }
    
    /**
     * Reseta todos os campos editaveis da interface grafica.
     */
    private void resetaValores(){
        txt_placa.setText("");
        txt_ano.setText("");
        txt_valorDiaria.setText("");
        txt_cargMax.setText("");
        txt_medKmLt.setText("");
        txt_numEixos.setText("");
        txt_numPass.setText("");
        txt_numPort.setText("");
        txt_categoria.setText("");
        check_ar.setSelected(false);
        check_wifi.setSelected(false);
    }
    
    /**
     * Caso a opcao de marcar "carro" for true, desabilita todos os campos que editaveis
     * que tenham relacoes com onibus e caminhao. 
     * @param evt
     */
    private void check_carroActionPerformed(java.awt.event.ActionEvent evt) {
        if(check_carro.isSelected()){
            opsOnibus(false);
            opsCaminhao(false);
            check_ar.setEnabled(true);
            txt_numPass.setEnabled(true);
        }else{
            opsOnibus(true);
            opsCaminhao(true);
        }
    }

    /**
     * Caso a opcao de marcar "caminhao" for true, desabilita todos os campos que editaveis
     * que tenham relacoes com onibus e carro. 
     * @param evt
     */
    private void check_caminhaoActionPerformed(java.awt.event.ActionEvent evt) {

        if(check_caminhao.isSelected()){
            opsOnibus(false);
            opsCarro(false);
        }else{
            opsCarro(true);
            opsOnibus(true);
        }
    }

    
    /**
     * Caso a opcao de marcar "onibus" for true, desabilita todos os campos que editaveis
     * que tenham relacoes com caminhao e carro. 
     * @param evt
     */
    private void check_onibusActionPerformed(java.awt.event.ActionEvent evt) {
        if(check_onibus.isSelected()){
            opsCarro(false);
            opsCaminhao(false);
            check_ar.setEnabled(true);
            txt_numPass.setEnabled(true);
        }else{
            opsCarro(true);
            opsCaminhao(true);
        }
    }

    /**
     * Evento caso o botao salvar seja preciosado, se o cadastro ocrrer com sucesso,
     * mostra uma mensagem de sucesso. Caso contrario, mostra uma mensagem de falha.
     * @param evt
     */
    private void btn_salvaActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Veiculo novoVeiculo = salvaVeiculo();
            veiculos.add(novoVeiculo);
            
            JOptionPane.showMessageDialog(null, "VEICULO CADASTRADO COM SUCESSO");
            
            resetaValores();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "DIGITE AS INFORMACOES DE FORMA CORRETA");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salva;
    private javax.swing.JCheckBox check_ar;
    private javax.swing.JCheckBox check_caminhao;
    private javax.swing.JCheckBox check_carro;
    private javax.swing.JCheckBox check_onibus;
    private javax.swing.JCheckBox check_wifi;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelAr;
    private javax.swing.JLabel labelCarga;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelEixos;
    private javax.swing.JLabel labelMedia;
    private javax.swing.JLabel labelPassa;
    private javax.swing.JLabel labelPlaca;
    private javax.swing.JLabel labelPor;
    private javax.swing.JLabel labelValor;
    private javax.swing.JLabel labelWifi;
    private javax.swing.JTextField txt_ano;
    private javax.swing.JTextField txt_cargMax;
    private javax.swing.JTextField txt_categoria;
    private javax.swing.JTextField txt_medKmLt;
    private javax.swing.JTextField txt_numEixos;
    private javax.swing.JTextField txt_numPass;
    private javax.swing.JTextField txt_numPort;
    private javax.swing.JTextField txt_placa;
    private javax.swing.JTextField txt_valorDiaria;
    // End of variables declaration//GEN-END:variables
}
