/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 * Interface Grafica menu
 * @author Bruno and Matheus
 */
public class Menu extends javax.swing.JFrame {
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JArea = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuNovaLocacao = new javax.swing.JMenuItem();
        menuBuscaLocacao = new javax.swing.JMenuItem();
        menuListLocacoes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuNovoCliente = new javax.swing.JMenuItem();
        menuBuscarCliente = new javax.swing.JMenuItem();
        menuListClientes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuNovoVeiculo = new javax.swing.JMenuItem();
        menuBuscarVeiculo = new javax.swing.JMenuItem();
        menuListaVeiculos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color2"));
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(720, 480));

        JArea.setMaximumSize(new java.awt.Dimension(1920, 1080));
        JArea.setMinimumSize(new java.awt.Dimension(720, 480));
        JArea.setPreferredSize(new java.awt.Dimension(1920, 1080));
        JArea.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        jLabel1.setText("Minha Locadora");

        JArea.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JAreaLayout = new javax.swing.GroupLayout(JArea);
        JArea.setLayout(JAreaLayout);
        JAreaLayout.setHorizontalGroup(
            JAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JAreaLayout.createSequentialGroup()
                .addContainerGap(418, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(400, 400, 400))
        );
        JAreaLayout.setVerticalGroup(
            JAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JAreaLayout.createSequentialGroup()
                .addContainerGap(329, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(303, 303, 303))
        );

        jMenuBar1.setAutoscrolls(true);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(355, 35));

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_document.png"))); // NOI18N
        jMenu2.setText("Gerenciar Locações");

        menuNovaLocacao.setText("Nova Locação");
        menuNovaLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovaLocacaoActionPerformed(evt);
            }
        });
        jMenu2.add(menuNovaLocacao);

        menuBuscaLocacao.setText("Buscar Locação");
        menuBuscaLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscaLocacaoActionPerformed(evt);
            }
        });
        jMenu2.add(menuBuscaLocacao);

        menuListLocacoes.setText("Lista de Locações");
        menuListLocacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListLocacoesActionPerformed(evt);
            }
        });
        jMenu2.add(menuListLocacoes);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon_user.png"))); // NOI18N
        jMenu3.setText("Gerenciar Clientes");

        menuNovoCliente.setText("Novo Cliente");
        menuNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoClienteActionPerformed(evt);
            }
        });
        jMenu3.add(menuNovoCliente);

        menuBuscarCliente.setText("Buscar Cliente");
        menuBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarClienteActionPerformed(evt);
            }
        });
        jMenu3.add(menuBuscarCliente);

        menuListClientes.setText("Lista de Clientes");
        menuListClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListClientesActionPerformed(evt);
            }
        });
        jMenu3.add(menuListClientes);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconcar.png"))); // NOI18N
        jMenu4.setText("Gerenciar Veículos");
        jMenu4.setToolTipText("");

        menuNovoVeiculo.setText("Novo Veículo");
        menuNovoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNovoVeiculoActionPerformed(evt);
            }
        });
        jMenu4.add(menuNovoVeiculo);

        menuBuscarVeiculo.setText("Buscar Veículo");
        menuBuscarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarVeiculoActionPerformed(evt);
            }
        });
        jMenu4.add(menuBuscarVeiculo);

        menuListaVeiculos.setText("Lista de Veículos");
        menuListaVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListaVeiculosActionPerformed(evt);
            }
        });
        jMenu4.add(menuListaVeiculos);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JArea, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JArea, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1094, 757));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Acao do sistema ao clicar na opcao "Busca Veiculo" no menu de veiculos.
     * @param evt
     */
    private void menuBuscarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {
        BuscarVeiculo buscarVeiculo = new BuscarVeiculo();
        JArea.add(buscarVeiculo);
        buscarVeiculo.setVisible(true);
    }
    
    /**
     * Acao do sistema ao clicar na opcao "Novo Veiculo" no menu de veiculos.
     * @param evt
     */
    private void menuNovoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {
        CadastroVeiculo novoVeiculo = new CadastroVeiculo();
        JArea.add(novoVeiculo);
        novoVeiculo.setVisible(true);
    }

    /**
     * Acao do sistema ao clicar na opcao "Lista de Veiculos" no menu de locacoes.
     * @param evt
     */
    private void menuListaVeiculosActionPerformed(java.awt.event.ActionEvent evt) {
        ListaVeiculos listaVeiculo = new ListaVeiculos();
        JArea.add(listaVeiculo);
        listaVeiculo.setVisible(true);
    }

    /**
     * Acao do sistema ao clicar na opcao "Buscar Cliente" no menu de clientes.
     * @param evt
     */
    private void menuBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {
        BuscarCliente novaBusca = new BuscarCliente();
        JArea.add(novaBusca);
        novaBusca.setVisible(true);
    }

    /**
     * Acao do sistema ao clicar na opcao "Novo Cliente" no menu de clientes.
     * @param evt
     */
    private void menuNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {
        CadastroCliente novoCliente = new CadastroCliente();
        JArea.add(novoCliente);
        novoCliente.setVisible(true);
    }
    
    /**
     * Acao do sistema ao clicar na opcao "nova locacao" no menu de locacoes.
     * @param evt
     */
    private void menuNovaLocacaoActionPerformed(java.awt.event.ActionEvent evt) {
        CadastroLocacao novaLocacao = new CadastroLocacao();
        JArea.add(novaLocacao);
        novaLocacao.setVisible(true);
    }

    /**
     * Acao do sistema ao clicar na opcao "Buscar Locacao" no menu de locacoes.
     * @param evt
     */
    private void menuBuscaLocacaoActionPerformed(java.awt.event.ActionEvent evt) {
        BuscarLocacao buscarLocacao = new BuscarLocacao();
        JArea.add(buscarLocacao);
        buscarLocacao.setVisible(true);
    }

    /**
     * Acao do sistema ao clicar na opcao "Lista de Locacoes" no menu de locacoes.
     * @param evt
     */
    private void menuListLocacoesActionPerformed(java.awt.event.ActionEvent evt) {
        ListLocacoes listaLocacoes = new ListLocacoes();
        JArea.add(listaLocacoes);
        listaLocacoes.setVisible(true);
    }

    /**
     * Acao do sistema ao clicar na opcao "Buscar Locacao" no menu de locacoes.
     * @param evt
     */
    private void menuListClientesActionPerformed(java.awt.event.ActionEvent evt) {
        ListaClientes listaClientes = new ListaClientes();
        JArea.add(listaClientes);
        listaClientes.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane JArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuBuscaLocacao;
    private javax.swing.JMenuItem menuBuscarCliente;
    private javax.swing.JMenuItem menuBuscarVeiculo;
    private javax.swing.JMenuItem menuListClientes;
    private javax.swing.JMenuItem menuListLocacoes;
    private javax.swing.JMenuItem menuListaVeiculos;
    private javax.swing.JMenuItem menuNovaLocacao;
    private javax.swing.JMenuItem menuNovoCliente;
    private javax.swing.JMenuItem menuNovoVeiculo;
    // End of variables declaration//GEN-END:variables
}
